### ISSUE TITLE
ImportError: cannot import name 'TypedDict'

### ISSUE THREAD

**Issue by MasaKusuda** [eggplants/pixiv-bulk-downloader#6]
TypedDictがimportできないエラー
python>=3.8にすることで解決しそう
参考：https://docs.python.org/3/whatsnew/3.8.html#typing

```
pixiv-bulk-downloader on main via 🐍 v3.6.3
❯ pbd
Traceback (most recent call last):
  File "/home/masahiro/.pyenv/versions/3.6.3/bin/pbd", line 7, in <module>
    from pbd.main import main
  File "/home/masahiro/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pbd/__init__.py", line 1, in <module>
    from .base import PixivBaseDownloader  # noqa: F401
  File "/home/masahiro/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pbd/base.py", line 6, in <module>
    from gppt import LoginInfo
  File "/home/masahiro/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gppt/__init__.py", line 1, in <module>
    from .auth import PixivAuth  # noqa: F401
  File "/home/masahiro/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gppt/auth.py", line 8, in <module>
    from .login_response_types import LoginCred, LoginInfo, PixivLoginFailed
  File "/home/masahiro/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gppt/login_response_types.py", line 1, in <module>
    from typing import TypedDict
ImportError: cannot import name 'TypedDict'
```

**Comment by MasaKusuda** [comment]
python3.8.12に変更してから再度pbdをインストールし直して実行してみるが、エラー
これはいまいち解決方法がわからず、localのpython側から実行するのは諦めました。
Dockerだとうまく動きました。
```
pixiv-bulk-downloader on main via 🐍 v3.8.12 took 6s
❯ pbd
Traceback (most recent call last):
  File "/home/masahiro/.pyenv/versions/3.8.12/bin/pbd", line 5, in <module>
    from pbd.main import main
  File "/home/masahiro/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pbd/__init__.py", line 1, in <module>
    from .base import PixivBaseDownloader  # noqa: F401
  File "/home/masahiro/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pbd/base.py", line 6, in <module>
    from gppt import LoginInfo
  File "/home/masahiro/.pyenv/versions/3.8.12/lib/python3.8/site-packages/gppt/__init__.py", line 1, in <module>
    from .auth import PixivAuth  # noqa: F401
  File "/home/masahiro/.pyenv/versions/3.8.12/lib/python3.8/site-packages/gppt/auth.py", line 9, in <module>
    from .selenium import GetPixivToken
  File "/home/masahiro/.pyenv/versions/3.8.12/lib/python3.8/site-packages/gppt/selenium.py", line 35, in <module>
    REQUESTS_KWARGS: dict[str, Any] = {
TypeError: 'type' object is not subscriptable
```

**Comment by eggplants** [comment]
- [x] Drop Python<3.8
- [ ] (type commentに)切り替えていく

**Comment by eggplants** [comment]
```bash
pip show pixiv-bulk-downloader
```
はどうなりますか？
おそらく古いpixiv-bulk-downloaderが入っていると思います。

**Comment by MasaKusuda** [comment]
以下の通りになります。
```
❯ pip show pixiv-bulk-downloader
Name: pixiv-bulk-downloader
Version: 2.1
Summary: Pixiv Bulk Downloader
Home-page: https://github.com/eggplants/pixiv-bulk-downloader
Author: eggplants
Author-email: None
License: MIT
Location: /home/masahiro/.pyenv/versions/3.8.12/lib/python3.8/site-packages
Requires: stdiomask, gppt, pixivpy
Required-by:
```

**Comment by MasaKusuda** [comment]
README.mdに記載されている以下の点について、何もしていないのが原因かもしれません。
具体的にどのようにsetupするかご教授いただけますでしょうか。

> Note: In advance, please setup google-chrome-stable + selenium + webdriver

**Comment by eggplants** [comment]
エラーの理由がわかりました。

>TypeError: 'type' object is not subscriptable

gpptでは型注釈に`dict`を使ってますが、これはPython3.9からの書き方なので、「型の文脈で関数を使うな」と怒られています。

**Comment by eggplants** [comment]
v2.2で思い切って`python_requires`をPython3.9以上にしました。

**Comment by eggplants** [comment]
See: https://pypi.org/project/pixiv-bulk-downloader/2.2/
